<?php
/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * This file has been generated by the Sonata EasyExtends bundle ( http://sonata-project.org/easy-extends )
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{

    /**
     * @var integer $id
     */
    protected $id;
    
    /**
     * @var string $address
     */
    private $address;
    
    /**
     * @var string $firstname
     */
    private $firstname;
    
    /**
     * @var string $lastname
     */
    private $lastname;
    
    /**
     * @var string $phone
     */
    private $phone;
    
    /**
     * @var string $mobile
     */
    private $mobile;
    
    /**
     * @var Dodici\Fansworld\WebBundle\Entity\Country
     */
    private $country;
    
    /**
     * @var Dodici\Fansworld\WebBundle\Entity\City
     */
    private $city;
    
    /**
     * @var Application\Sonata\MediaBundle\Entity\Media
     */
    private $image;
    
    /**
     * @var array $privacy
     * array (
     * 'fieldname' => Privacy::EVERYONE|Privacy::FRIENDS_ONLY,
     * ...
     * )
     */
    private $privacy;

	/**
     * @var ArrayCollection $friendships
     */
    protected $friendships;
    
    public function __construct()
    {
        parent::__construct();
    	$this->friendships = new ArrayCollection();
        $this->privacy = array();
    }
    
    public function __toString()
    {
    	if ($this->getFirstname() || $this->getLastname()) {
    		return join(' ', array($this->getFirstname(), $this->getLastname()));
    	} else {
    		return $this->getUsername() ?: $this->getEmail();
    	}
    }
    
    /**
     * Get id
     *
     * @return integer $id
     */
    public function getId()
    {
        return $this->id;
    }
    
    /**
     * Set address
     *
     * @param string $address
     */
    public function setAddress($address)
    {
        $this->address = $address;
    }

    /**
     * Get address
     *
     * @return string 
     */
    public function getAddress()
    {
        return $this->address;
    }

    /**
     * Set firstname
     *
     * @param string $firstname
     */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;
    }

    /**
     * Get firstname
     *
     * @return string 
     */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
     * Set lastname
     *
     * @param string $lastname
     */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;
    }

    /**
     * Get lastname
     *
     * @return string 
     */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
     * Set phone
     *
     * @param string $phone
     */
    public function setPhone($phone)
    {
        $this->phone = $phone;
    }

    /**
     * Get phone
     *
     * @return string 
     */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
     * Set mobile
     *
     * @param string $mobile
     */
    public function setMobile($mobile)
    {
        $this->mobile = $mobile;
    }

    /**
     * Get mobile
     *
     * @return string 
     */
    public function getMobile()
    {
        return $this->mobile;
    }

    /**
     * Set privacy
     *
     * @param array $privacy
     */
    public function setPrivacy($privacy)
    {
        $this->privacy = $privacy;
    }

    /**
     * Get privacy
     *
     * @return array 
     */
    public function getPrivacy()
    {
        return $this->privacy;
    }

    /**
     * Set country
     *
     * @param Dodici\Fansworld\WebBundle\Entity\Country $country
     */
    public function setCountry(\Dodici\Fansworld\WebBundle\Entity\Country $country)
    {
        $this->country = $country;
    }

    /**
     * Get country
     *
     * @return Dodici\Fansworld\WebBundle\Entity\Country 
     */
    public function getCountry()
    {
        return $this->country;
    }

    /**
     * Set city
     *
     * @param Dodici\Fansworld\WebBundle\Entity\City $city
     */
    public function setCity(\Dodici\Fansworld\WebBundle\Entity\City $city)
    {
        $this->city = $city;
    }

    /**
     * Get city
     *
     * @return Dodici\Fansworld\WebBundle\Entity\City 
     */
    public function getCity()
    {
        return $this->city;
    }

    /**
     * Set image
     *
     * @param Application\Sonata\MediaBundle\Entity\Media $image
     */
    public function setImage(\Application\Sonata\MediaBundle\Entity\Media $image)
    {
        $this->image = $image;
    }

    /**
     * Get image
     *
     * @return Application\Sonata\MediaBundle\Entity\Media 
     */
    public function getImage()
    {
        return $this->image;
    }

    /**
     * Add friendships
     *
     * @param Dodici\Fansworld\WebBundle\Entity\Friendship $friendships
     */
    public function addFriendship(\Dodici\Fansworld\WebBundle\Entity\Friendship $friendships)
    {
        $this->friendships[] = $friendships;
    }
	public function addFriendships(\Dodici\Fansworld\WebBundle\Entity\Friendship $friendships)
    {
        $this->addFriendship($friendships);
    }

    /**
     * Get friendships
     *
     * @return Doctrine\Common\Collections\Collection 
     */
    public function getFriendships()
    {
        return $this->friendships;
    }
    
	/**
     * Set friendships
     *
     * @param Doctrine\Common\Collections\Collection $friendships
     */
    public function setFriendships($friendships)
    {
        $this->friendships = $friendships;
    }

}