imports:
    - { resource: parameters.ini }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    charset:         UTF-8
    router:          { resource: "%kernel.root_dir%/config/routing.yml" }
    form:            true
    csrf_protection: true
    validation:      { enable_annotations: true }
    templating:      { engines: ['twig'] } #assets_version: SomeVersionScheme
    session:
        default_locale: %locale%
        auto_start:     true

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%

jms_security_extra:
    secure_controllers:  true
    secure_all_services: false
    
fos_user:
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\Sonata\UserBundle\Entity\User
    group:
        group_class: Application\Sonata\UserBundle\Entity\Group
    registration:
        form:
            type: app_user_registration
        confirmation:
            enabled:    true
    profile:
        form:
            type: app_user_profile
    from_email:
        address:        info@fansworld.tv
        sender_name:    Fansworld
    service:
        mailer:         fos_user.mailer.twig_swift
    
fos_js_routing:
    routes_to_expose: [ ^((?!_admin_).)*$ ]
    
sonata_user:
    security_acl: true
    
stof_doctrine_extensions:
    default_locale: es_ES
    translation_fallback: true
    orm:
        default:
            sluggable:      true
            translatable:   true

jms_i18n_routing:
    default_locale: es
    locales: [en, es]
    strategy: prefix_except_default
    
sonata_media:
    db_driver: doctrine_orm # or doctrine_mongodb
    default_context: default
    contexts:
        default:  # the default context is mandatory
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file

            formats:
                avatar: { width: 50 , height: 50 , quality: 70}
                small: { width: 100 , quality: 70}
                small_square: { width: 100, height: 100 , quality: 75}
                wall: { width: 150 , quality: 75}
                medium: { width: 250 , quality: 80}
                big:   { width: 500 , quality: 85, constraint: false}
                huge:   { width: 1024 , quality: 90, constraint: false}

    cdn:
        server:
            path: /uploads/media # http://media.sonata-project.org/

    filesystem:
        local:
            directory:  %kernel.root_dir%/../web/uploads/media
            create:     false
            
sonata_admin:
    title:      Fansworld
    title_logo: /bundles/dodicifansworldadmin/images/logo_title.png
    templates:
        layout:  DodiciFansworldAdminBundle::standard_layout.html.twig
        user_block: DodiciFansworldAdminBundle:Core:user_block.html.twig
    security:
        handler: sonata.admin.security.handler.role
        
fos_facebook:
    file:   %kernel.root_dir%/../vendor/facebook/src/base_facebook.php
    alias:  facebook
    app_id: %facebook.app_id%
    secret: %facebook.app_secret%
    cookie: true
    permissions: [email, user_birthday, user_location]
    
artseld_openinviter:
    username: "fansworld"
    private_key: "6c0b090b7bf71fa484ab40de80beb21a"
    plugins_cache_time: "1800"
    plugins_cache_file: "oi_plugins.php"
    cookie_path: "../web/uploads"
    local_debug: "on_error"
    remote_debug: ""
    hosted: ""
    proxies: []
    stats: ""
    stats_user: ""
    stats_password: ""
    update_files: "1"
    transport: "curl"

parameters:
    sonata.user.admin.user.class: Application\Sonata\UserBundle\Admin\Entity\UserAdmin
    sonata.media.resizer.simple.class: Application\Sonata\MediaBundle\Media\SimpleResizer
        
services:
    ### BEGIN ADMIN SERVICES ###
    dodici.fansworld.adminbundle.admin.country:
        class: Dodici\Fansworld\AdminBundle\Admin\CountryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: country }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Country, DodiciFansworldAdminBundle:CountryAdmin]
    dodici.fansworld.adminbundle.admin.city:
        class: Dodici\Fansworld\AdminBundle\Admin\CityAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: city }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\City, DodiciFansworldAdminBundle:CityAdmin]
    dodici.fansworld.adminbundle.admin.friendship:
        class: Dodici\Fansworld\AdminBundle\Admin\FriendshipAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: friendship }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Friendship, DodiciFansworldAdminBundle:FriendshipAdmin]
    dodici.fansworld.adminbundle.admin.newscategory:
        class: Dodici\Fansworld\AdminBundle\Admin\NewsCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: newscategory }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\NewsCategory, DodiciFansworldAdminBundle:NewsCategoryAdmin]
    dodici.fansworld.adminbundle.admin.newspost:
        class: Dodici\Fansworld\AdminBundle\Admin\NewsPostAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: newspost }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\NewsPost, DodiciFansworldAdminBundle:NewsPostAdmin]
    dodici.fansworld.adminbundle.admin.video:
        class: Dodici\Fansworld\AdminBundle\Admin\VideoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: video }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Video, DodiciFansworldAdminBundle:VideoAdmin]
    dodici.fansworld.adminbundle.admin.videocategory:
        class: Dodici\Fansworld\AdminBundle\Admin\VideoCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: videocategory }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\VideoCategory, DodiciFansworldAdminBundle:VideoCategoryAdmin]
    dodici.fansworld.adminbundle.admin.comment:
        class: Dodici\Fansworld\AdminBundle\Admin\CommentAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: comment }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Comment, DodiciFansworldAdminBundle:CommentAdmin]
    dodici.fansworld.adminbundle.admin.photo:
        class: Dodici\Fansworld\AdminBundle\Admin\PhotoAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: photo }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Photo, DodiciFansworldAdminBundle:PhotoAdmin]
    dodici.fansworld.adminbundle.admin.album:
        class: Dodici\Fansworld\AdminBundle\Admin\AlbumAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: album }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Album, DodiciFansworldAdminBundle:AlbumAdmin]
    dodici.fansworld.adminbundle.admin.interestcategory:
        class: Dodici\Fansworld\AdminBundle\Admin\InterestCategoryAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: interestcategory }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\InterestCategory, DodiciFansworldAdminBundle:InterestCategoryAdmin]
    dodici.fansworld.adminbundle.admin.interest:
        class: Dodici\Fansworld\AdminBundle\Admin\InterestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: interest }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Interest, DodiciFansworldAdminBundle:InterestAdmin]
    dodici.fansworld.adminbundle.admin.contest:
        class: Dodici\Fansworld\AdminBundle\Admin\ContestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: contest }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Contest, DodiciFansworldAdminBundle:ContestAdmin]
    dodici.fansworld.adminbundle.admin.contestparticipant:
        class: Dodici\Fansworld\AdminBundle\Admin\ContestParticipantAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: contestparticipant }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\ContestParticipant, DodiciFansworldAdminBundle:ContestParticipantAdmin]
    dodici.fansworld.adminbundle.admin.idolship:
        class: Dodici\Fansworld\AdminBundle\Admin\IdolshipAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: idolship }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Idolship, DodiciFansworldAdminBundle:IdolshipAdmin]
    dodici.fansworld.adminbundle.admin.level:
        class: Dodici\Fansworld\AdminBundle\Admin\LevelAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: level }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Level, DodiciFansworldAdminBundle:LevelAdmin]
    dodici.fansworld.adminbundle.admin.friendgroup:
        class: Dodici\Fansworld\AdminBundle\Admin\FriendGroupAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: friendgroup }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\FriendGroup, DodiciFansworldAdminBundle:FriendGroupAdmin]
    dodici.fansworld.adminbundle.admin.complaint:
        class: Dodici\Fansworld\AdminBundle\Admin\ComplaintAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: complaint }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\Complaint, DodiciFansworldAdminBundle:ComplaintAdmin]
    dodici.fansworld.adminbundle.admin.hasinterest:
        class: Dodici\Fansworld\AdminBundle\Admin\HasInterestAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: dodicifansworldadminbundle, label: hasinterest }
        arguments: [null, Dodici\Fansworld\WebBundle\Entity\HasInterest, DodiciFansworldAdminBundle:HasInterestAdmin]
    ### END ADMIN SERVICES ###
    liking.listener.persist:
        class: Dodici\Fansworld\WebBundle\Listener\LikingCountUpdater
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    liking.listener.remove:
        class: Dodici\Fansworld\WebBundle\Listener\LikingCountUpdater
        tags:
            - { name: doctrine.event_listener, event: postRemove }
    tag.listener.persist:
        class: Dodici\Fansworld\WebBundle\Listener\TagUpdater
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    tag.listener.remove:
        class: Dodici\Fansworld\WebBundle\Listener\TagUpdater
        tags:
            - { name: doctrine.event_listener, event: postRemove }
    notificator.listener.persist:
        class: Dodici\Fansworld\WebBundle\Listener\Notificator
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    notificator.listener.update:
        class: Dodici\Fansworld\WebBundle\Listener\Notificator
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
    score.listener.persist:
        class: Dodici\Fansworld\WebBundle\Listener\ScoreHandler
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    score.listener.update:
        class: Dodici\Fansworld\WebBundle\Listener\ScoreHandler
        tags:
            - { name: doctrine.event_listener, event: postUpdate }
    score.listener.remove:
        class: Dodici\Fansworld\WebBundle\Listener\ScoreHandler
        tags:
            - { name: doctrine.event_listener, event: postRemove }
    comment.listener.persist:
        class: Dodici\Fansworld\WebBundle\Listener\CommentCountUpdater
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    comment.listener.remove:
        class: Dodici\Fansworld\WebBundle\Listener\CommentCountUpdater
        tags:
            - { name: doctrine.event_listener, event: postRemove }
    album.listener.persist:
        class: Dodici\Fansworld\WebBundle\Listener\AlbumImageSetter
        tags:
            - { name: doctrine.event_listener, event: postPersist }
    album.listener.remove:
        class: Dodici\Fansworld\WebBundle\Listener\AlbumImageSetter
        tags:
            - { name: doctrine.event_listener, event: postRemove }
    notification.listener.mailer:
        class: Dodici\Fansworld\WebBundle\Listener\NotificationMailer
        tags:
            - { name: doctrine.event_listener, event: postPersist }
        arguments:
            - "@service_container"
    my.facebook.user:
        class: Dodici\Fansworld\WebBundle\Security\FacebookProvider
        arguments:
            facebook: "@fos_facebook.api"
            userManager: "@app_user.user_manager"
            validator: "@validator"
            container: "@service_container"
    appstate:
      class: Dodici\Fansworld\WebBundle\Extensions\AppState
      arguments: [@security.context, @doctrine.orm.entity_manager]
    tagger:
      class: Dodici\Fansworld\WebBundle\Extensions\Tagger
      arguments: [@doctrine.orm.entity_manager]
    sharer:
      class: Dodici\Fansworld\WebBundle\Extensions\Sharer
      arguments: [@doctrine.orm.entity_manager]
    commenter:
      class: Dodici\Fansworld\WebBundle\Extensions\Commenter
      arguments: [@doctrine.orm.entity_manager]
    complainer:
      class: Dodici\Fansworld\WebBundle\Extensions\Complainer
      arguments: [@doctrine.orm.entity_manager]
    user.location:
      class: Dodici\Fansworld\WebBundle\Extensions\UserLocation
      arguments: [@doctrine.orm.entity_manager]
    contact.importer:
      class: Dodici\Fansworld\WebBundle\Extensions\ContactImporter
      arguments: [@service_container]
    twig.extension.appstate:
      class: Dodici\Fansworld\WebBundle\Extensions\AppStateExtension
      arguments: [@appstate]
      tags:
          - { name: twig.extension }
    flumotion.api.request:
      class: Flumotion\APIBundle\Builder\RequestBuilder
      arguments: [ @doctrine, %flumotion.api_url%, %flumotion.api_key%, %flumotion.api_secret% ]
    flumotion.ftp:
      class: Flumotion\APIBundle\Ftp\FtpWriter
      arguments: [ @flumotion.api.request, %flumotion.ftp_host%, %flumotion.ftp_path%, %flumotion.ftp_file%, %flumotion.ftp_user%, %flumotion.ftp_pass% ]
    flumotiontwig:
      class: Flumotion\APIBundle\Extensions\FlumotionTwig
      arguments: [@session, @doctrine.orm.entity_manager, @flumotion.api.request, %flumotion.player_baseurl%, %flumotion.player_video_baseurl%]
    twig.extension.flumotiontwig:
      class: Flumotion\APIBundle\Extensions\FlumotionTwigExtension
      arguments: [@flumotiontwig]
      tags:
          - { name: twig.extension }
    twig.extension.text:
      class: Twig_Extensions_Extension_Text
      tags:
          - { name: twig.extension }
    app_user.registration.form.type:
        class: Application\Sonata\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_registration }
    app_user.profile.form.type:
        class: Application\Sonata\UserBundle\Form\Type\ProfileFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: app_user_profile }
    app_user.user_manager:
        class: Application\Sonata\UserBundle\Entity\UserManager
        public: false
        arguments: [@security.encoder_factory, @fos_user.util.username_canonicalizer, @fos_user.util.email_canonicalizer, @fos_user.entity_manager, %fos_user.model.user.class%]