imports:
    - { resource: config.yml }

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug

# Swiftmailer spooling
swiftmailer:
    spool:
        type: file
        path: "%kernel.root_dir%/spool"

#snc_redis:
#    clients:
#        default:
#            type: predis
#            alias: default
#            dsn: { host: %snc_redis_dsn% }
#            logging: %kernel.debug%
#    session:
#        client: default
#        prefix: foo
#        use_as_default: true
#    doctrine:
#        metadata_cache:
#            client: cache
#            entity_manager: default
#            document_manager: default
#        result_cache:
#            client: cache
#            entity_manager: default
#            document_manager: default
#            namespace: "dcrc:"
#        query_cache:
#            client: cache
#            entity_manager: default
#    swiftmailer:
#        client: default
#        key: swiftmailer