services:
    kaltura:
      class: Kaltura\APIBundle\Services\Kaltura
      arguments: [%kaltura.partner_id%, %kaltura.subpartner_id%, %kaltura.user_secret%, %kaltura.admin_secret%, %kaltura.username%, %kaltura.stream_url%, %kaltura.api_url%]
    kaltura.notification:
      class: Kaltura\APIBundle\Services\NotificationManager
      arguments: [@kaltura, @logger, @doctrine.orm.entity_manager]
    kalturatwig:
      class: Kaltura\APIBundle\Services\KalturaTwig
      arguments: [@kaltura, @visitator, @service_container, %kaltura.player_id%]
    twig.extension.kalturatwig:
      class: Kaltura\APIBundle\Extensions\KalturaTwigExtension
      arguments: [@kalturatwig]
      tags:
          - { name: twig.extension }