<?php

namespace Dodici\Fansworld\WebBundle\Model;

use Doctrine\DBAL\Types\Type;

use Application\Sonata\UserBundle\Entity\User;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends CountBaseRepository
{
	public function wallEntity($entity, $limit = null, $offset = null)
	{
		if ($entity instanceof \Application\Sonata\UserBundle\Entity\User) {
    		$classname = 'target';
    	} else {
    		$exp = explode('\\', get_class($entity));
    		$classname = strtolower(end($exp));
    	}
    	
		$query = $this->_em->createQuery('
    	SELECT c, cc
    	FROM \Dodici\Fansworld\WebBundle\Entity\Comment c
    	LEFT JOIN c.comments cc
    	WHERE c.'.$classname.' = :entity
    	AND c.active = true
    	AND c.comment IS NULL
    	ORDER BY c.createdAt DESC, cc.createdAt DESC
    	')
        	->setParameter('entity', $entity->getId(), Type::BIGINT);
        
        if ($limit !== null)
            $query = $query->setMaxResults((int)$limit);
        if ($offset !== null)
            $query = $query->setFirstResult((int)$offset);
        
        return $query->getResult();
	}
}