<?php

namespace Dodici\Fansworld\WebBundle\Model;

use Doctrine\DBAL\Types\Type;

use Doctrine\ORM\EntityRepository;

/**
 * ComplaintRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ComplaintRepository extends CountBaseRepository
{
	/**
     * Has the user already complained?
     */
    public function UserAndEntity(\Application\Sonata\UserBundle\Entity\User $user, $entity)
    {
    	if ($entity instanceof \Application\Sonata\UserBundle\Entity\User) {
    		return false;
    	}
    	
    	$exp = explode('\\', get_class($entity));
    	$classname = strtolower(end($exp));
    	if (strpos($classname, 'proxy') !== false) {
    		$classname = str_replace(array('dodicifansworldwebbundleentity','proxy'), array('',''), $classname);
    	}
    	
    	return $this->_em->createQuery('
    	SELECT ct
    	FROM \Dodici\Fansworld\WebBundle\Entity\Complaint ct
    	WHERE
    	ct.author = :user
    	AND
    	ct.'.$classname.' = :entity
    	')
    		->setParameter('user', $user->getId(), Type::BIGINT)
    		->setParameter('entity', $entity->getId(), Type::BIGINT)
    		->getResult();
    }
}