<?php

namespace Dodici\Fansworld\WebBundle\Model;

use Application\Sonata\UserBundle\Entity\User;

use Dodici\Fansworld\WebBundle\Entity\Team;

use Doctrine\ORM\EntityRepository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends CountBaseRepository
{
	public function byTeam(Team $team, $limit=null, $offset=null)
	{
		$query = $this->_em->createQuery('
    	SELECT e, ht
    	FROM \Dodici\Fansworld\WebBundle\Entity\Event e
    	JOIN e.hasteams ht
    	WHERE
    	e.active = true AND ht.team = :team
    	ORDER BY e.userCount DESC, e.fromtime ASC
    	')
    		->setParameter('team', $team->getId());
    		
    	if ($limit !== null) $query = $query->setMaxResults($limit);
    	if ($offset !== null) $query = $query->setFirstResult($offset);
    	
    	return $query->getResult();
	}
	
	public function byIdol(User $user, $limit=null, $offset=null)
	{
		$query = $this->_em->createQuery('
    	SELECT e, hu
    	FROM \Dodici\Fansworld\WebBundle\Entity\Event e
    	JOIN e.hasusers hu
    	WHERE
    	e.active = true AND hu.target = :user
    	ORDER BY e.userCount DESC, e.fromtime ASC
    	')
    		->setParameter('user', $user->getId());
    		
    	if ($limit !== null) $query = $query->setMaxResults($limit);
    	if ($offset !== null) $query = $query->setFirstResult($offset);
    	
    	return $query->getResult();
	}
	
}