<?php

namespace Dodici\Fansworld\WebBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * LevelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LevelRepository extends CountBaseRepository
{
	public function byScore($minscore) 
	{
		return $this->_em->createQuery('
    	SELECT l
    	FROM \Dodici\Fansworld\WebBundle\Entity\Level l
    	WHERE
    	:score >= l.minimum AND l.active = true
    	ORDER BY l.minimum DESC
    	')
    		->setParameter('score', $minscore)
    		->setMaxResults(1)
    		->getOneOrNullResult();
	}
}