<?php

namespace Dodici\Fansworld\WebBundle\Model;

use Doctrine\ORM\EntityRepository;
use Dodici\Fansworld\WebBundle\Entity;

/**
 * LikingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikingRepository extends CountBaseRepository
{
	public function byUserAndEntity(\Application\Sonata\UserBundle\Entity\User $user, $entity) {
		$relation = $this->getType($entity); 
		
    	return $this->findBy(array('author' => $user->getId(), $relation => $entity->getId()));
	}
}