<?php

namespace Dodici\Fansworld\WebBundle\Model;

use Doctrine\ORM\EntityRepository;
use Dodici\Fansworld\WebBundle\Entity;

/**
 * LikingRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LikingRepository extends CountBaseRepository
{
	public function byUserAndEntity(\Application\Sonata\UserBundle\Entity\User $user, $entity) {
		$exp = explode('\\', get_class($entity));
		$relation = strtolower(end($exp));
		if (strpos($relation, 'proxy') !== false) {
    		$relation = str_replace(array('dodicifansworldwebbundleentity','proxy'), array('',''), $relation);
    	}
    	
    	return $this->findBy(array('author' => $user->getId(), $relation => $entity->getId()));
	}
}