<?php

namespace Dodici\Fansworld\WebBundle\Model;

use Doctrine\DBAL\Types\Type;

use Doctrine\ORM\EntityRepository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NotificationRepository extends CountBaseRepository
{
	/**
     * Get notifications for user
     */
    public function latest(\Application\Sonata\UserBundle\Entity\User $user, $readed = null, $limit = null, $offset = null)
    {
    	$query = $this->_em->createQuery('
    	SELECT n
    	FROM \Dodici\Fansworld\WebBundle\Entity\Notification n
    	WHERE
    	n.target = :userid AND n.active=true
    	'
    	. ($readed !== null ? ' AND n.readed = :readed ' : '') .
    	'
    	ORDER BY n.readed DESC, n.createdAt DESC
    	'
    	)
    		->setParameter('userid', $user->getId(), Type::BIGINT);

    	if ($readed !== null)
		$query = $query->setParameter('readed', $readed, Type::BOOLEAN);
    	
    	if ($limit !== null)
    	$query = $query->setMaxResults($limit);
    	
    	if ($offset !== null)
    	$query = $query->setFirstResult($offset);
    		
    	return $query->getResult();
    }
    
	/**
     * Count notifications for user
     */
    public function countLatest(\Application\Sonata\UserBundle\Entity\User $user, $readed = null)
    {
    	$query = $this->_em->createQuery('
    	SELECT COUNT(n.id)
    	FROM \Dodici\Fansworld\WebBundle\Entity\Notification n
    	WHERE
    	n.target = :userid AND n.active=true
    	'
    	. ($readed !== null ? ' AND n.readed = :readed ' : '')
    	)
    		->setParameter('userid', $user->getId(), Type::BIGINT);
    		
    	if ($readed !== null)
		$query = $query->setParameter('readed', $readed, Type::BOOLEAN);
    		
    	return (int)$query->getSingleScalarResult();
    }
}