<?php

namespace Dodici\Fansworld\WebBundle\Model;

use Doctrine\ORM\EntityRepository;

/**
 * TeamshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamshipRepository extends CountBaseRepository
{
	public function byUser(User $user, $limit=null, $offset=null)
	{
		$query = $this->_em->createQuery('
    	SELECT ts, t
    	FROM \Dodici\Fansworld\WebBundle\Entity\Teamship ts
    	JOIN ts.team t
    	WHERE
    	t.active = true AND ts.author = :user
    	ORDER BY t.fanCount DESC, ts.score DESC
    	')
    		->setParameter('user', $user->getId());
    		
    	if ($limit !== null) $query = $query->setMaxResults($limit);
    	if ($offset !== null) $query = $query->setFirstResult($offset);
    	
    	return $query->getResult();
	}
}